-- CREATE TABLE student(
--     student_id INT,
--     name VARCHAR(20) NOT NULL,
--     major VARCHAR(20) UNIQUE,
--     PRIMARY KEY(student_id)
    
-- );


-- DROP TABLE student

-- ALTER table student ADD gpa DECIMAL(3,2);
-- ALTER TABLE student DROP COLUMN gpa;

-- DESCRIBE student;
-- select * FROM student

-- ------------Inserting data --------------

-- INSERT INTO student VALUES(1, 'Jack', 'Biology');
-- INSERT INTO student VALUES(2, 'Kate', 'Sociology');
-- INSERT INTO student(student_id, name) VALUES(3, NULL);
INSERT INTO student VALUES(4, 'Jack', 'Biology');
-- INSERT INTO student VALUES(5, 'Mike', 'Computer Science');
